version: '3.8'

services:
  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "5030:8080"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend